config/routes.rb
Rails.application.routes.draw do
  devise_for :org_people, :controllers => {
                            :registrations => "org_people/registrations",
                            :sessions => "org_people/sessions",
                            :passwords => "org_people/passwords",
                            :confirmations => "confirmations",
                          }

  devise_scope :org_person do
    get "signup", to: "org_people/registrations#new"
    get "signin", to: "org_people/sessions#new"
    delete "signout", to: "org_people/sessions#destroy"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :catalogues
  root "catalogues#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_one :org_person
	belongs_to :org_product
end

app/models/org_company.rb
class OrgCompany < ApplicationRecord
  has_and_belongs_to_many :org_contacts
  has_many :org_persons
  has_many :org_products
  belongs_to :typ_company, foreign_key: "typ_company_id"
end

app/models/org_contact.rb
class OrgContact < ApplicationRecord
    has_and_belongs_to_many :org_people, foreign_key: "org_person_id"
	has_and_belongs_to_many :org_companies, foreign_key: "org_company_id"
	belongs_to :typ_contact, foreign_key: "typ_contact_id"
	belongs_to :typ_country, foreign_key: "typ_country_id"
	belongs_to :typ_region, foreign_key: "typ_region_id"
end

app/models/org_person.rb
class OrgPerson < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_and_belongs_to_many :org_contacts
  # belongs_to :org_company, foreign_key: "org_company_id"
  # belongs_to :typ_position, foreign_key: "typ_position_id"
  # accepts_nested_attributes_for :typ_position
end

app/models/org_product.rb
class OrgProduct < ApplicationRecord
    belongs_to :org_company, foreign_key: "org_company_id"
	belongs_to :typ_category, foreign_key: "typ_category_id"
	belongs_to :typ_subcategory, foreign_key: "typ_subcategory_id"
end

app/models/trx_order.rb
class TrxOrder < ApplicationRecord
    has_many :TrxOrderItem
	has_many :TrxOrderFee
	belongs_to :bill_to_contact, class_name: 'OrgContact'
end

app/models/trx_order_fee.rb
class TrxOrderFee < ApplicationRecord
    belongs_to :TrxOrder, foreign_key: "trx_order_id"
end

app/models/trx_order_item.rb
class TrxOrderItem < ApplicationRecord
    belongs_to :org_company, foreign_key: "org_company_id"
	belongs_to :TrxOrder, foreign_key: "trx_order_id"
	belongs_to :OrgProduct, foreign_key: "org_product_id"
end

app/models/typ_category.rb
class TypCategory < ApplicationRecord
    has_many :org_products
	has_many :typ_subcategory
end

app/models/typ_company.rb
class TypCompany < ApplicationRecord
    has_many :org_companies
end

app/models/typ_contact.rb
class TypContact < ApplicationRecord
    has_many :org_contacts
end

app/models/typ_country.rb
class TypCountry < ApplicationRecord
    has_many :org_contact
	has_many :typ_region
end

app/models/typ_fee.rb
class TypFee < ApplicationRecord
    has_many :TrxOrderFee
end

app/models/typ_position.rb
class TypPosition < ApplicationRecord
    has_many :org_people
end

app/models/typ_region.rb
class TypRegion < ApplicationRecord
    belongs_to :typ_country, foreign_key: "typ_country_id"
	has_many :org_contacts
	has_many :typ_sales_taxes
end

app/models/typ_sales_tax.rb
class TypSalesTax < ApplicationRecord
    belongs_to :typ_region, foreign_key: "typ_region_id"
	belongs_to :typ_tax, foreign_key: "typ_tax_id"
end

app/models/typ_subcategory.rb
class TypSubcategory < ApplicationRecord
    belongs_to :typ_category, foreign_key: "typ_category_id"
	has_many :org_products
end

app/models/typ_tax.rb
class TypTax < ApplicationRecord
    has_many :typ_sales_taxes
end

app/helpers/catalogues_helper.rb
module CataloguesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase)
    html = <<-HTML
    <div class="alert alert-danger">
        #{sentence}
    </div>
    <div class="alert-error alert-block register-error">
        #{messages}
    </div>
    HTML
    html.html_safe
  end
end

app/views/layouts/_footer.html.erb
<div id="push"></div>
<footer class="footer fixed-bottom">
  <div class="container">
    <nav>
      <ul>
        <%# <li></li>
      <li></li> %>
        <li><%= link_to  "Contact Us", "#" %></li>
        <li><%= link_to  "Terms of Use", "#" %></li>
        <li><%= link_to  "Privacy Policy", "#" %></li>
        <li><%= link_to  "How it Works", "#" %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="fixed-top navbar navbar-dark bg-dark navbar-expand-lg d-flex">
  <div class="container container-fluid">
    <%= link_to  "ProjectMeals", root_path, id: "logo", class: "text-decoration-none" %>
    <span class="beta">Beta</span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    </button>
    <div class="collapse navbar-collapse flex-row-reverse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to  "Shopping Cart", "#", class: "nav-link" %>
        </li>
        <% if signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to  "Profile", "#", class: "dropdown-item" %>
              </li>
              <li class="divider"></li>
              <li><%= link_to  "Sign out", "#", class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to  "Sign in", signin_path, class: "nav-link" %></li>
        <%end%>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectMeal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <% render "layouts/shim" %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render "layouts/header" %>
    <div class="container-fluid">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
          <%= msg %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <div class="row">
        <%= yield :sidebar %>
        <%= yield %>
      </div>
    </div>
    <%= render "layouts/footer" %>
    <% debug(params) if Rails.env.development? %>
  </body>
</html>